# Note: Parameters can be hardcoded directly in 'deploy-functions.yaml'
# if you do not need to vary them between your functions!
description: "Function to deploy rest extractor"
owner: CDF Bootcamp Team
cpu: 1.0
memory: 1.5
env_vars: {"COGNITE_BASE_URL": "https://westeurope-1.cognitedata.com",
  "COGNITE_PROJECT": "slb-test",
  "COGNITE_TOKEN_URL": "https://login.microsoftonline.com/45472a8e-6a12-4531-97d8-1f38f5d553a4/oauth2/v2.0/token",
  }
data_set_id: 3010655221386586
